
services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app
